[Interface]
PrivateKey = [HUB_PRIVATEKEY]  # Clave privada de este nodo
Address = 10.10.10.1/24          # IP del nodo dentro de la VPN
ListenPort = 51820               # Puerto UDP en el que escucha WireGuard

PostUp = sysctl -w net.ipv4.ip_forward=1; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = [PEER_PUBLICKEY]     # Clave pública del coordinador (hub)
Endpoint = [IP_ADDRESS]:51820        # IP pública y puerto del coordinador
AllowedIPs = 10.10.10.2/32       # Rango de IPs enrutadas por el túnel
PersistentKeepalive = 25         # Envía un ping cada 25s para mantener la conexión activa

[Peer]
PublicKey = [PEER_PUBLICKEY]   
Endpoint = [IP_ADDRESS]:51820 
AllowedIPs = 10.10.10.3/32       
PersistentKeepalive = 25         

[Peer]
PublicKey = [PEER_PUBLICKEY]   
Endpoint = [IP_ADDRESS]:51820  
AllowedIPs = 10.10.10.4/32 
PersistentKeepalive = 25         
