[Interface]
PrivateKey = [PEER_PRIVATEKEY]
Address = 10.10.10.2/24
DNS = 1.1.1.1
ListenPort = 51820

[Peer]
PublicKey = [HUB_PUBLICKEY]
Endpoint = [IP_ADDRESS]:51820
AllowedIPs = 10.10.10.0/24
PersistentKeepalive = 25